Python bindings (#17)
Migrates in the Python bindings from [pash's vendored fork](https://github.com/angelhof/libdash/tree/ef6302502b904e33dd4cc686d71142fb1a87bbbd).

Resolves issues from #9 and #13.

Significantly expanded tests, with conformance tests to ensure that the OCaml and Python bindings agree.

diff --git a/ocaml/Makefile b/ocaml/Makefile
--- a/ocaml/Makefile
+++ b/ocaml/Makefile
@@ -2,35 +2,37 @@ BUILD=$(abspath ../_build/lib)
 
 .PHONY : all install clean
 
-all : dash.cmxa dash.cma META
+all : dash.cmxa META shell_to_json json_to_shell
 
 install : all
-	ocamlfind install libdash META dash.cmxa dash.cma dash.a dash.mli dash.cmi dash.cmo dash.cmx ast.mli ast.cmi ast.cmo ast.cmx
+	ocamlfind install libdash META dash.cmxa dash.cma dash.a dash.mli dash.cmi dash.cmo dash.cmx ast.mli ast.cmi ast.cmo ast.cmx shell_to_json json_to_shell
 
 META : mk_meta.sh
 	./mk_meta.sh
 
+shell_to_json: dash.cmxa ast_json.mli ast_json.ml shell_to_json.ml
+	ocamlfind ocamlopt -g -thread -package threads,str,atdgen,ctypes,ctypes.foreign -linkpkg -cclib -L$(BUILD) -cclib -ldash $^ -o $@
+
+json_to_shell: dash.cmxa ast_json.mli ast_json.ml json_to_shell.ml
+	ocamlfind ocamlopt -g -thread -package threads,str,atdgen,ctypes,ctypes.foreign -linkpkg -cclib -L$(BUILD) -cclib -ldash $^ -o $@
+
+ast_json.mli: ast_json.ml
+
+ast_json.ml : ast_atd.atd
+	atdgen -j -j-std ast_atd.atd
+	sed -i -e '/type char = Ast.char/d' ast_atd_j.ml
+	sed -i -e '/type char = Ast.char/d' ast_atd_j.mli
+	mv ast_atd_j.ml $@
+	mv ast_atd_j.mli $(subst ml,mli,$@)
+
 dash.cmxa : dash.mli dash.ml ast.mli ast.ml
-	ocamlfind ocamlmklib -g -package threads,str,ctypes,ctypes.foreign -L$(BUILD) -ldash $^ -o dash
+	ocamlfind ocamlmklib -g -package str,ctypes,ctypes.foreign -L$(BUILD) -ldash $^ -o dash
 
-test : test.native test.byte $(wildcard ../test/tests/*)
-	@echo "TESTING test.native"
-	@for f in ../test/tests/*; do \
-		LD_LIBRARY_PATH=$(BUILD) ../test/round_trip.sh ./test.native $$f 2>test.err; \
-	done
-	@echo "TESTING test.byte"
-	@for f in ../test/tests/*; do \
-		LD_LIBRARY_PATH=$(BUILD) ../test/round_trip.sh ./test.byte $$f 2>test.err; \
-	done
-
-test.native : test.ml dash.cmxa
-	LD_LIBRARY_PATH=$(BUILD) ocamlfind ocamlopt -g -thread -package threads,str,ctypes,ctypes.foreign -linkpkg -ccopt -L$(BUILD) -ccopt -Wl,-rpath -ccopt -Wl,$(BUILD) -cclib -ldash dash.cmxa test.ml -o $@
-
-test.byte : test.ml dash.cmxa
-	LD_LIBRARY_PATH=$(BUILD) ocamlfind ocamlc -g -thread -package threads,str,ctypes,ctypes.foreign -linkpkg -I $(BUILD) -ccopt -L$(BUILD) -dllpath $(BUILD) -cclib -ldash dash.cma test.ml -o $@
-
-test.ml : ../test/test.ml
-	cp $< $@
+test : $(wildcard ../test/*)
+	@type json_to_shell >/dev/null 2>&1 && type shell_to_json >/dev/null 2>&1 || $(MAKE) json_to_shell shell_to_json
+	@find ../test/tests ../test/pash_tests -type f | while read f; do ../test/round_trip.sh ./rt.sh "$$f"; done | tee ocaml.log
+	@cat ocaml.log | egrep '^[A-Z0-9_]+:' | cut -d ':' -f 1 | sort | uniq -c
+	@grep ':' ocaml.log && echo "FAILED" && exit 1 || exit 0
 
 clean :
 	rm -f *.o *.cmo *.cmi *.cmx dash.a dash.cma dash.cmxa
